# Generated by Django 4.1.7 on 2023-03-07 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None)),
                ('address1', models.CharField(max_length=288)),
                ('address2', models.CharField(max_length=288)),
                ('pin_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=124)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent')], default='customer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
