# Generated by Django 4.1.7 on 2023-03-09 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('work_in_progress', 'Work in progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_by', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('solved_by', models.CharField(max_length=128)),
                ('solved_date', models.DateTimeField(blank=True, null=True)),
                ('complaint_file', models.FileField(blank=True, upload_to='complaint_file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
