# Generated by Django 4.1.7 on 2023-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0002_complaintmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='solved_by',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
