# Generated by Django 4.1.7 on 2023-03-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0004_remove_complaintmodel_solved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmodel',
            name='solved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
