# Generated by Django 4.1.7 on 2023-03-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0006_complaintmodel_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='comments',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
