# Generated by Django 4.1.7 on 2023-03-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0007_alter_complaintmodel_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='complaint_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
